version: '3'

services:
  squid:
    image: ubuntu/squid:latest
    container_name: squid-proxy
    expose:
      - "3128"
    volumes:
      - ./squid/squid.conf:/etc/squid/squid.conf
      - ./passwd:/etc/squid/passwd
    restart: unless-stopped

  tls:
    image: nginx:alpine
    container_name: squid-tls
    ports:
      - "8443:8443"
    volumes:
      - ./nginx/stream.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - squid
    restart: unless-stopped